[package]
name = "birthday-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.9", features = ["postgres"] }
envy = "0.4"
dotenvy = "0.15"
poise = "0.6.1"
tokio = "1.44.2"
