[package]
name = "birthday-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.9", features = ["postgres"] }
dotenvy = "0.15"
serenity = "0.12"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
