// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDate;
#[derive(Queryable, Debug)]
pub struct Guild {
    pub id: i32,
    pub snowflake: String,
    pub birthday_role: String,
}

#[derive(Queryable, Debug)]
pub struct Member {
    pub id: i32,
    pub snowflake: String,
    pub birthday: NaiveDate,
}

#[derive(Queryable, Debug)]
pub struct MemberGuild {
    pub id: i32,
    pub member_id: i32,
    pub guild_id: i32,
}

